# Generated by Django 6.0.3 on 2026-03-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('profile_picture', models.URLField(blank=True, max_length=500, null=True)),
                ('past_illness', models.JSONField(blank=True, default=list)),
                ('past_symptoms', models.JSONField(blank=True, default=list)),
                ('allergy', models.CharField(blank=True, max_length=255)),
                ('family_disease', models.JSONField(blank=True, default=dict)),
                ('job_type', models.CharField(blank=True, max_length=100)),
                ('water_consumption', models.CharField(blank=True, max_length=50)),
                ('coffee_tea', models.CharField(blank=True, max_length=50)),
                ('smoking', models.CharField(blank=True, max_length=50)),
                ('alcohol', models.CharField(blank=True, max_length=50)),
                ('sleep_hours', models.CharField(blank=True, max_length=50)),
                ('stress_level', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
